### PR TITLE
merge duplicated edges in Gearpump's DAG

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by huafengw** [comment]
@pangolulu
I merged duplicated edges in Gearpump's DAG, please help to verify this pull request to see whether it works.

**Comment by gy910210** [comment]
@huafengw 
OK, thanks.

**Comment by gy910210** [comment]
@huafengw 

I test on Vertical Hoeffding Tree, it works now, supported with `topological order with circles` and `merge duplicated edges`.

**Comment by huafengw** [comment]
@pangolulu then please help review this pull request

**Pull request merged**
